CREATE TABLE geoinfra.gdp (
    year integer,
    austriahungary integer,
    belgium integer,
    bulgaria integer,
    denmark integer,
    finland integer,
    france integer,
    germany integer,
    greece integer,
    italy integer,
    netherlands integer,
    norway integer,
    portugal integer,
    romania integer,
    russia integer,
    serbia integer,
    spain integer,
    sweden integer,
    switzerland integer,
    turkey integer,
    uk integer,
    europe integer,
    usa integer
);
